#!/usr/bin/env node
var fs = require('fs'),
		spawn = require('child_process').spawn,
		querystring = require('querystring'),
		request = require('request');
		path = require('path'),	
		prefix = path.join(process.env['HOME'], '/.webgetopts/');


function usage(metadata) {
		console.log(metadata.site, "[options]");
		metadata.options.split(",").forEach(function(v) {
			var field = v.replace(":", "");
			console.log("\t", "--" + field, "\t", "arguments for", field);		
		});	
}


function install(metadata) {
	var templateFile = path.join(prefix, 'template');
	var filename = path.join(prefix, metadata.site);
	console.log("Found the following WebGetOpts:");
	console.log(JSON.stringify(metadata, null, 4 ));
	console.log();
	var template = fs.createReadStream(templateFile);
	template.on('error', function(error){console.log(error);});	
	var webstub = fs.createWriteStream(filename);
	template.pipe(webstub, {end: true});	
	template.on('end', function() {
			fs.appendFile(filename, JSON.stringify(metadata, null, 4), function(err) {
				if (err) {
					throw err;
				}
				var chmod = spawn('chmod', ['u+x', filename]);
				chmod.stdin.on('data', function(data) {
					console.log(data.toString());
					});
				chmod.stdout.on('data', function(data) {
					console.log(data.toString());
					});
				chmod.stderr.on('data', function(data) {
					console.log(data.toString());
					});
				chmod.on('exit', function() {
					console.log("Created webstub with name ", metadata.site);
					console.log("Saved to", filename);
					console.log("You may now use any of the following arguments:");
					console.log();
					usage(metadata);
				});
				});
			});
}

if (process.argv[2] == "install") {
	var overrides = {};
	if (process.argv.length > 4 && process.argv[4].length >= 1) {
		overrides["site"] = process.argv[4];
	}
	var wclisaver = require('./wgosaver');
	var site = process.argv[3];
	var metadata = wclisaver.fetch(site, overrides, install);
		
} else {
	argParser = function(args) {
		return args.reduce(function(parameters, argument ){
				if (parameters.isOption) {
					parameters.data[parameters.option] = argument;	
					parameters.isOption = false;
				}
				if (argument.indexOf("--") != -1) {
					parameters.option = argument.substring(2);
					parameters.isOption = true;
				} else if (argument.indexOf("-") != -1) {
					parameters.option = argument.substring(1);
					parameters.isOption = true;
				}
				return parameters;
				}, { option: "", isOption: false, data: {} }
	);
}
var site = process.argv[2];
if (process.argv.length > 3) {
	var file = spawn("sed", ["1d",  site]); // remove shebang
	file.stdout.on('data', function(data) {
			var schema = JSON.parse(data.toString()); 
			var args = process.argv.slice(3);

			// args = args.map(function(arg){ return (arg.indexOf("-") == -1 ? "\"" + arg + "\"" : arg) });
			file.stdin.end();
			file.stdout.end();
			var params = ["-o","ox", "-l", schema.options].concat(["-n", schema.site, "--"].concat( args));
			var getopt = spawn("getopt", params);
			var errors = "";
			getopt.stderr.on('data', function(err) {
				errors = errors += err.toString();
			});	
			getopt.stdout.on('data', function(out) {
				getopt.on('exit', function(code) {
					if (code == 1) {
						console.log("Error: Invalid parameters, cannot make request.");
						console.log(errors);	
						usage(schema);
						return;
					}
					var parsed = argParser(args);
					var encoded = querystring.stringify(parsed.data);	
					var submit = { method: 'post', url: schema.target,
					 form: parsed.data, headers: { 'Accept': 'application/json' }
					};
	console.log();
	console.log(submit.method.toUpperCase(), submit.url);
	console.log(">\t", encoded);
	
	request(submit, function(error, response, body) {
		var type = response.headers['content-type'];
		console.log();
		console.log("< Received", type);
		if (type == 'application/json') {
			console.log(JSON.stringify(JSON.parse(body), null, 4));	
		} else {
			console.log(body);
		}
		})
	});	
	});	
});

	file.stdout.on('exit', function(data) {
			console.log('exit');
			});
	}
}
